data:
  train_files: /home/jeffg/data/gsm8k/train.parquet
  val_files: /home/jeffg/data/gsm8k/test.parquet
  train_batch_size: 1024
  val_batch_size: 1312
  max_prompt_length: 512
  max_response_length: 1024

actor_rollout_ref:
  model:
    path: /home/jeffg/llama-4-scout-instruct
    use_remove_padding: True
    enable_gradient_checkpointing: True
  actor:
    optim:
      lr: 1e-6
    ppo_mini_batch_size: 256
    ppo_micro_batch_size_per_gpu: 4
    ppo_max_token_len_per_gpu: 24000
    use_dynamic_bsz: True
    use_kl_loss: True
    kl_loss_coef: 0.001
    kl_loss_type: low_var_kl
    fsdp_config:
      param_offload: True
      optimizer_offload: True
      grad_offload: True
      wrap_policy:
        min_num_params: 20000000

  ref:
    fsdp_config:
      param_offload: True
      wrap_policy:
        min_num_params: 20000000

  rollout:
    tensor_model_parallel_size: 1
    name: vllm
    gpu_memory_utilization: 0.7
    n: 16

algorithm:
  adv_estimator: grpo
  kl_ctrl:
    kl_coef: 0.001

trainer:
  critic_warmup: 0
  logger: console
  project_name: verl_grpo_example_gsm8k
  experiment_name: qwen2_7b_function_rm_kl1e-3
  val_before_train: False
  n_gpus_per_node: 8
  nnodes: 1
  save_freq: -1
  test_freq: 5
  total_epochs: 15
